#!/usr/bin/env bash
# Shared utility functions for repo-understand
# Bash 3.2 compatible -- no associative arrays, no readarray, no ${var,,}

# Colors (disabled if not a terminal)
if [ -t 1 ]; then
    COLOR_RESET='\033[0m'
    COLOR_GREEN='\033[0;32m'
    COLOR_YELLOW='\033[0;33m'
    COLOR_RED='\033[0;31m'
    COLOR_BLUE='\033[0;34m'
else
    COLOR_RESET=''
    COLOR_GREEN=''
    COLOR_YELLOW=''
    COLOR_RED=''
    COLOR_BLUE=''
fi

log_info() {
    printf "${COLOR_BLUE}[INFO]${COLOR_RESET} %s\n" "$1" >&2
}

log_success() {
    printf "${COLOR_GREEN}[OK]${COLOR_RESET}   %s\n" "$1" >&2
}

log_warn() {
    printf "${COLOR_YELLOW}[WARN]${COLOR_RESET} %s\n" "$1" >&2
}

log_error() {
    printf "${COLOR_RED}[ERR]${COLOR_RESET}  %s\n" "$1" >&2
}

# Human-readable file size
human_size() {
    local bytes="$1"
    if [ "$bytes" -ge 1048576 ] 2>/dev/null; then
        echo "$((bytes / 1048576)) MB"
    elif [ "$bytes" -ge 1024 ] 2>/dev/null; then
        echo "$((bytes / 1024)) KB"
    else
        echo "${bytes} B"
    fi
}

# Get file size in bytes (portable)
file_size_bytes() {
    local file="$1"
    if [ -f "$file" ]; then
        wc -c < "$file" | tr -d ' '
    else
        echo "0"
    fi
}

# Check if a command exists
require_command() {
    local cmd="$1"
    local install_hint="$2"
    if ! command -v "$cmd" >/dev/null 2>&1; then
        log_error "'$cmd' is required but not installed."
        if [ -n "$install_hint" ]; then
            log_error "Install with: $install_hint"
        fi
        exit 1
    fi
}

# Create directory if it does not exist
ensure_dir() {
    local dir="$1"
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
}

# Get ISO 8601 timestamp
iso_timestamp() {
    date -u '+%Y-%m-%dT%H:%M:%SZ'
}

# Get current git SHA (short) for a repo path
git_sha() {
    local repo_path="$1"
    if [ -d "$repo_path/.git" ] || git -C "$repo_path" rev-parse --git-dir >/dev/null 2>&1; then
        git -C "$repo_path" rev-parse --short HEAD 2>/dev/null || echo "unknown"
    else
        echo "unknown"
    fi
}

# Write the GENERATED header and YAML frontmatter to a file
# Usage: write_generated_header "Title" "purpose" "audience" "$sha" "$timestamp" > file
write_generated_header() {
    local title="$1"
    local purpose="$2"
    local audience="$3"
    local sha="$4"
    local timestamp="$5"
    cat <<HEADER
---
title: "$title"
purpose: "$purpose"
audience: "$audience"
generated_at: $timestamp
generated_from_sha: $sha
---
<!-- GENERATED by repo-understand.sh -- do not edit manually. Re-run the script to refresh. -->
HEADER
}

# Count total files in a directory (excluding .git)
count_files() {
    local dir="$1"
    find "$dir" -not -path '*/.git/*' -not -path '*/.git' -type f 2>/dev/null | wc -l | tr -d ' '
}

# Lowercase a string (bash 3.2 compatible)
to_lower() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

# Trim whitespace
trim() {
    echo "$1" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}
